version: '3'

services:
  app:
    #build: .
    image: 
    container_name: my-app 
    ports:
      - ""
    environment:
      - DATABASE_CLIENT=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_NAME=
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_SSL=
  db:
    image: postgres:latest
    container_name: my-db
    ports:
      - ""
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=